import type { EventCommand, SessionPhase } from "@/types/domain";

export const COMMAND_PHASES: Record<EventCommand, SessionPhase[]> = {
  open_session: ["lobby"],
  reveal_tea: ["welcome", "tasting"],
  start_timer: ["reveal", "brewing"],
  open_tasting: ["reveal", "brewing"],
  open_trivia: ["tasting"],
  close_trivia: ["trivia"],
  return_to_tasting: ["trivia"],
  next_tea: ["tasting", "trivia"],
  start_recap: ["tasting", "trivia"],
  advance_stage: ["lobby", "welcome", "reveal", "brewing", "tasting", "trivia"],
  start_brew: ["welcome"],
  restart_brew: ["brewing"],
  start_next_infusion: ["brewing"],
  end_brew_early: ["brewing"],
  pause_stage: ["welcome", "reveal", "brewing", "tasting", "trivia"],
  resume_stage: ["welcome", "reveal", "brewing", "tasting", "trivia"],
  extend_stage: ["brewing"],
  skip_stage: ["welcome", "reveal", "brewing", "tasting", "trivia"],
  go_back_stage: ["welcome", "reveal", "brewing", "tasting", "trivia"],
  jump_stage: ["welcome", "reveal", "brewing", "tasting", "trivia"],
  launch_breakouts:["tasting"],
  extend_breakouts:["tasting"],
  end_breakouts:["tasting"],
  open_discovery_card:["tasting"],
  compare_discovery_card:["tasting"],
  surface_discovery_curiosity:["tasting"],
  close_discovery_cards:["tasting"],
  invite_discovery_spokesperson:["tasting"],
  complete_discovery_share:["tasting"],
  reveal_group_aroma:["tasting"],
  reveal_group_taste:["tasting"],
  combine_group_reveal:["tasting"],
  show_group_timeline:["tasting"],
  set_group_timeline:["tasting"],
  highlight_group_flavor:["tasting"],
  clear_group_flavor:["tasting"],
  show_group_producer_notes:["tasting"],
  hide_group_producer_notes:["tasting"],
  freeze_group_fingerprint:["tasting"],
  return_group_discussion:["tasting"],
  open_cheers:["welcome","reveal","brewing","tasting","trivia","recap"],
  resolve_cheers:["welcome","reveal","brewing","tasting","trivia","recap"],
  cancel_cheers:["welcome","reveal","brewing","tasting","trivia","recap"],
  set_reward_mode:["welcome","reveal","brewing","tasting","trivia","recap"],
  grant_reward_completion:["welcome","reveal","brewing","tasting","trivia","recap"],
  set_conversation_prompts_enabled:["welcome","reveal","brewing","tasting","trivia","recap"],
  send_conversation_prompt:["welcome","reveal","brewing","tasting","trivia","recap"],
  configure_living_map:["tasting"],
  start_living_map:["tasting"],
  pause_living_map:["tasting"],
  resume_living_map:["tasting"],
  freeze_living_map:["tasting"],
  start_living_map_replay:["tasting"],
  pause_living_map_replay:["tasting"],
  resume_living_map_replay:["tasting"],
  seek_living_map_replay:["tasting"],
  commit_living_map_fingerprint:["tasting"],
  reopen_living_map:["tasting"],
  end_session: ["welcome", "reveal", "brewing", "tasting", "trivia", "recap"]
};

export function canRunCommand(phase: SessionPhase, command: EventCommand): boolean {
  return COMMAND_PHASES[command].includes(phase);
}

export function commandLabel(command: EventCommand): string {
  return ({
    open_session: "Open the tasting",
    reveal_tea: "Reveal tea",
    start_timer: "Start timer",
    open_tasting: "Open tasting",
    open_trivia: "Open trivia",
    close_trivia: "Close trivia",
    return_to_tasting: "Return to tasting",
    next_tea: "Next tea",
    start_recap: "Start recap",
    advance_stage: "Advance stage",
    start_brew: "Start shared brew",
    restart_brew: "Restart infusion",
    start_next_infusion: "Start next infusion",
    end_brew_early: "End brew early",
    pause_stage: "Pause stage",
    resume_stage: "Resume stage",
    extend_stage: "Extend stage",
    skip_stage: "Skip stage",
    go_back_stage: "Go back one stage",
    jump_stage: "Jump to stage",
    launch_breakouts:"Open tasting tables",
    extend_breakouts:"Extend tasting tables",
    end_breakouts:"Return tasting tables",
    configure_living_map:"Configure Living Map",
    start_living_map:"Start Living Map",
    pause_living_map:"Pause Living Map",
    resume_living_map:"Resume Living Map",
    freeze_living_map:"Freeze Living Map",
    start_living_map_replay:"Start Living Map replay",
    pause_living_map_replay:"Pause Living Map replay",
    resume_living_map_replay:"Resume Living Map replay",
    seek_living_map_replay:"Move Living Map replay",
    commit_living_map_fingerprint:"Commit Tasting Fingerprint",
    reopen_living_map:"Reopen Living Map",
    open_discovery_card:"Open table card",
    compare_discovery_card:"Compare table cards",
    surface_discovery_curiosity:"Surface table curiosity",
    close_discovery_cards:"Close table cards",
    invite_discovery_spokesperson:"Invite table spokesperson",
    complete_discovery_share:"Mark table story shared",
    reveal_group_aroma:"Reveal aroma portrait",
    reveal_group_taste:"Reveal taste portrait",
    combine_group_reveal:"Combine group portrait",
    show_group_timeline:"Open group timeline",
    set_group_timeline:"Move group timeline",
    highlight_group_flavor:"Highlight group flavor",
    clear_group_flavor:"Clear flavor highlight",
    show_group_producer_notes:"Open producer notes",
    hide_group_producer_notes:"Hide producer notes",
    freeze_group_fingerprint:"Freeze group fingerprint",
    return_group_discussion:"Return to discussion",
    open_cheers:"Open shared Cheers",
    resolve_cheers:"Resolve shared Cheers",
    cancel_cheers:"Cancel shared Cheers",
    set_reward_mode:"Change Gold Leaves reward mode",
    grant_reward_completion:"Grant completion exception",
    set_conversation_prompts_enabled:"Change conversation prompts",
    send_conversation_prompt:"Send conversation prompt",
    end_session: "End tasting"
  } satisfies Record<EventCommand, string>)[command];
}
