-- All identifiers/content below are synthetic fixture values, not exported rows.
CREATE FUNCTION extensions.gen_random_uuid() RETURNS uuid LANGUAGE sql AS $$ SELECT pg_catalog.gen_random_uuid() $$;
ALTER TABLE public.event_state_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
CREATE ROLE fixture_client;
GRANT USAGE ON SCHEMA public TO fixture_client;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO fixture_client;
INSERT INTO public.profiles(id,display_name,role) VALUES
 ('10000000-0000-0000-0000-000000000001','Synthetic host','admin'),
 ('10000000-0000-0000-0000-000000000002','Synthetic backup','host');
INSERT INTO public.merchant_wallets(id,owner_user_id,balance) VALUES
 ('11000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',1234);
INSERT INTO public.merchant_ledger_entries(wallet_id,transaction_id,entry_type,leaves_delta,balance_after,source,idempotency_key)
 VALUES('11000000-0000-0000-0000-000000000001',gen_random_uuid(),'adjustment',1234,1234,'fixture','fixture-baseline');
INSERT INTO public.live_tasting_reward_policies(id,rule_version,active,event_completion_leaves,max_leaves_per_participant_event,minimum_presence_seconds)
 VALUES('12000000-0000-0000-0000-000000000001','fixture-v1',true,10,10,0);
INSERT INTO public.teas(id,name) VALUES('20000000-0000-0000-0000-000000000001','Synthetic tea one'),('20000000-0000-0000-0000-000000000002','Synthetic tea two');
INSERT INTO public.teas(id,name) VALUES('20000000-0000-0000-0000-000000000003','Synthetic catalogue-only tea');
INSERT INTO public.tea_catalog_prices(product_id,canonical_tea_id,product_name,price_per_kilo_cents) VALUES('fixture-product','20000000-0000-0000-0000-000000000003','Synthetic catalogue-only tea',1000);
INSERT INTO public.events(id,title,slug,invite_code,starts_at,owner_user_id,host_user_id,backup_host_user_id)
 VALUES('30000000-0000-0000-0000-000000000001','Synthetic tasting','synthetic-tasting','FIXTURE-ONE',now(),'10000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002');
INSERT INTO public.event_flight_items(id,event_id,tea_id,position,reveal_title,reveal_description,brewing_instructions,steep_seconds)
 VALUES('31000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001',1,'Synthetic tea one','Synthetic reveal','Synthetic brewing',30),
 ('31000000-0000-0000-0000-000000000002','30000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000002',2,'Synthetic tea two','Synthetic reveal','Synthetic brewing',30);
UPDATE public.events SET current_flight_item_id='31000000-0000-0000-0000-000000000001';
INSERT INTO public.participants(id,event_id,user_id,display_name) VALUES
 ('40000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','Synthetic participant');
INSERT INTO public.tea_responses(id,participant_id,event_flight_item_id,personal_notes,completed_at)
 VALUES('41000000-0000-0000-0000-000000000001','40000000-0000-0000-0000-000000000001','31000000-0000-0000-0000-000000000001','Synthetic historical note',now());
INSERT INTO public.trivia_questions(id,event_flight_item_id,question,options,correct_index,position)
 VALUES('42000000-0000-0000-0000-000000000001','31000000-0000-0000-0000-000000000001','Synthetic historical question','["A","B"]',0,1);
INSERT INTO public.trivia_answers(participant_id,trivia_question_id,selected_index,is_correct,idempotency_key,original_answered_at,on_time)
 VALUES('40000000-0000-0000-0000-000000000001','42000000-0000-0000-0000-000000000001',0,true,gen_random_uuid(),now(),true);
INSERT INTO public.host_control_leases(event_id,holder_user_id,lease_token,expires_at)
 VALUES('30000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','50000000-0000-0000-0000-000000000001',now()+interval '1 day');
INSERT INTO public.event_breakout_sessions(id,event_id,event_flight_item_id,origin_stage,prompt,starts_at,ends_at,host_id)
 VALUES('60000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001','31000000-0000-0000-0000-000000000001','tasting','Synthetic prompt',now(),now()+interval '3 minutes','10000000-0000-0000-0000-000000000001');
INSERT INTO public.event_breakout_rooms(id,session_id,event_id,room_number,prompt)
 VALUES('61000000-0000-0000-0000-000000000001','60000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001',1,'Synthetic prompt');
INSERT INTO public.event_breakout_members(session_id,breakout_room_id,participant_id)
 VALUES('60000000-0000-0000-0000-000000000001','61000000-0000-0000-0000-000000000001','40000000-0000-0000-0000-000000000001');
UPDATE public.room_discovery_cards SET room_quote='Synthetic quote',room_quote_attributed=true,room_quote_participant_id='40000000-0000-0000-0000-000000000001',spokesperson_participant_id='40000000-0000-0000-0000-000000000001',spokesperson_state='accepted';
INSERT INTO public.room_discovery_card_items(card_id,category,item_text,normalized_key,source,prevalence_total,created_by)
 SELECT id,'shared','Synthetic item','synthetic','participant',1,'40000000-0000-0000-0000-000000000001' FROM public.room_discovery_cards;
INSERT INTO public.event_live_reward_awards(event_id,participant_id,user_id,reward_type,amount,rule_version,idempotency_key,status)
 VALUES('30000000-0000-0000-0000-000000000001','40000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','event_complete',10,'fixture-v1','fixture-reward','queued');
INSERT INTO public.tasting_sessions(id,owner_user_id) VALUES('70000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001');
INSERT INTO public.tasting_cards(id,session_id,owner_user_id,canonical_tea_id,tea_name_snapshot,rating)
 VALUES('71000000-0000-0000-0000-000000000001','70000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001','Synthetic card',4);
INSERT INTO public.merchant_listings(id,source_card_id,creator_id,tea_identity_key,canonical_tea_id,tea_name,creator_display_name,source_tier,pricing_source,calculated_leaf_price,source_tastings)
 VALUES('72000000-0000-0000-0000-000000000001','71000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','fixture-tea','20000000-0000-0000-0000-000000000001','Synthetic listing','Synthetic creator','polychrome','flat_rate',5,2);
