"use client";

import {useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/browser";
import {LivingTastingMap} from "@/components/live/LivingTastingMap";
import {
  LIVING_MAP_PROMPTS,livingMapElapsedMs,livingMapReplayPositionMs,livingMapReplayProjection,type LivingMapSnapshot,type LivingMapVisibilityMode
} from "@/lib/living-tasting-map";
import type {HostCommandPayload} from "@/lib/host-command";
import type {ConductorStage,EventCommand} from "@/types/domain";

export function HostLivingTastingMap({eventId,stage,busy,enabled,onCommand}:{eventId:string;stage:ConductorStage;busy:boolean;enabled:boolean;onCommand:(command:EventCommand,payload?:HostCommandPayload)=>Promise<void>}){
  const[snapshot,setSnapshot]=useState<LivingMapSnapshot|null>(null);const[durationSeconds,setDurationSeconds]=useState(720);const[visibilityMode,setVisibilityMode]=useState<LivingMapVisibilityMode>("quiet_start");const[customNotesEnabled,setCustomNotesEnabled]=useState(true);
  const[now,setNow]=useState<number|null>(null);const[seek,setSeek]=useState(0);const[moderationError,setModerationError]=useState("");
  const refresh=useCallback(async()=>{const response=await fetch(`/api/events/${eventId}/living-map`,{cache:"no-store"});if(!response.ok)return;const result=await response.json() as {snapshot:LivingMapSnapshot|null};setSnapshot(result.snapshot);if(result.snapshot){setDurationSeconds(result.snapshot.session.durationSeconds);setVisibilityMode(result.snapshot.session.visibilityMode);setCustomNotesEnabled(result.snapshot.session.customNotesEnabled);if(result.snapshot.session.status==="replaying")setSeek(Math.round(livingMapReplayPositionMs(result.snapshot.session,Date.now())))}},[eventId]);
  useEffect(()=>{const first=window.setTimeout(()=>void refresh(),0);const poll=window.setInterval(()=>void refresh(),2500);return()=>{window.clearTimeout(first);window.clearInterval(poll)}},[refresh]);
  useEffect(()=>{const client=createClient();const channel=client.channel(`host-living-map-${eventId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"living_tasting_map_snapshots",filter:`event_id=eq.${eventId}`},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel)}},[eventId,refresh]);
  useEffect(()=>{const first=window.setTimeout(()=>setNow(Date.now()),0);const timer=window.setInterval(()=>setNow(Date.now()),250);return()=>{window.clearTimeout(first);window.clearInterval(timer)}},[]);
  if(!["aroma","first_sip","explore","discuss","reveal","debrief"].includes(stage))return null;
  const session=snapshot?.session??null;const elapsed=session?livingMapElapsedMs(session,now??0):0;const replayPosition=session?livingMapReplayPositionMs(session,now??0):0;
  const projection=snapshot?.replay&&session?.status==="replaying"?livingMapReplayProjection(snapshot.replay.events,snapshot.projection.participantTotal,replayPosition):snapshot?.projection??null;
  const issueCommand=async(command:EventCommand,payload?:HostCommandPayload)=>{await onCommand(command,payload);window.setTimeout(()=>void refresh(),100)};
  async function moderate(flavorKey:string,operation:"hide"|"restore"){
    setModerationError("");try{const response=await fetch(`/api/events/${eventId}/living-map`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"moderate_flavor",operation,flavorKey,reason:"Host map moderation"})});const result=await response.json() as {snapshot?:LivingMapSnapshot;error?:string};if(!response.ok){setModerationError(result.error??"That phrase could not be changed.");return}if(result.snapshot)setSnapshot(result.snapshot)}catch{setModerationError("The moderation update could not reach the room.")}
  }
  return <section className="card host-living-map" aria-labelledby="host-living-map-title"><div className="card-header"><div><p className="eyebrow">Signature centrepiece · event-stream projection</p><h2 className="card-title" id="host-living-map-title">The Living Tasting Map</h2><p>Conduct the rhythm and protect the discovery. The visible map contains anonymous aggregates only.</p></div><span className={`chip ${session?.status==="live"?"chip-live":""}`}>{session?.status??"ready"}</span></div>
    {!session||session.status==="ready"?<div className="host-living-map-config"><label>Round length<select value={durationSeconds} onChange={event=>setDurationSeconds(Number(event.target.value))}><option value={600}>10 minutes</option><option value={720}>12 minutes · recommended</option><option value={900}>15 minutes</option></select></label><label>Visibility<select value={visibilityMode} onChange={event=>setVisibilityMode(event.target.value as LivingMapVisibilityMode)}><option value="quiet_start">Quiet Start · discovery default</option><option value="shared_live">Shared Live · social</option></select></label><label className="checkbox-row"><input type="checkbox" checked={customNotesEnabled} onChange={event=>setCustomNotesEnabled(event.target.checked)}/> Allow personal phrases</label><div className="row"><button className="btn btn-secondary" type="button" disabled={!enabled||busy} onClick={()=>void issueCommand("configure_living_map",{durationSeconds,visibilityMode,customNotesEnabled})}>Save map setup</button><button className="btn btn-primary btn-attention" type="button" disabled={!enabled||busy||stage!=="aroma"} onClick={()=>void issueCommand("start_living_map")}>Start twelve-minute map</button></div>{stage!=="aroma"&&<p className="help">The start control opens during Aroma.</p>}</div>:<>
      <div className="host-living-map-metrics"><div><strong>{formatClock(Math.max(0,session.durationSeconds*1000-elapsed))}</strong><span>remaining</span></div><div><strong>{snapshot?.projection.aromaContributors??0}</strong><span>aroma contributors</span></div><div><strong>{snapshot?.projection.tasteContributors??0}</strong><span>taste contributors</span></div><div><strong>{snapshot?.projection.items.length??0}</strong><span>active patterns</span></div></div>
      {projection&&<LivingTastingMap projection={projection} groupVisible={session.status==="frozen"||session.status==="replaying"||session.status==="committed"?true:Boolean(snapshot?.groupVisible)} ariaLabel="Host view of the anonymous Living Tasting Map"/>}
      <div className="host-living-map-controls">
        {session.status==="live"&&<><button className="btn btn-secondary" disabled={!enabled||busy} onClick={()=>void issueCommand("pause_living_map")}>Pause map</button><button className="btn btn-primary btn-attention" disabled={!enabled||busy} onClick={()=>void issueCommand("freeze_living_map")}>Freeze ending</button></>}
        {session.status==="paused"&&<><button className="btn btn-primary" disabled={!enabled||busy} onClick={()=>void issueCommand("resume_living_map")}>Resume map</button><button className="btn btn-primary btn-attention" disabled={!enabled||busy} onClick={()=>void issueCommand("freeze_living_map")}>Freeze ending</button></>}
        {session.status==="frozen"&&<><button className="btn btn-primary btn-attention" disabled={!enabled||busy||!snapshot?.replay} onClick={()=>void issueCommand("start_living_map_replay")}>Replay tasting evolution</button><button className="btn btn-quiet" disabled={!enabled||busy} onClick={()=>void issueCommand("reopen_living_map")}>Reopen briefly</button></>}
        {session.status==="replaying"&&<><button className="btn btn-secondary" disabled={!enabled||busy} onClick={()=>void issueCommand(session.replayPausedAt?"resume_living_map_replay":"pause_living_map_replay")}>{session.replayPausedAt?"Resume replay":"Pause replay"}</button><button className="btn btn-primary btn-attention" disabled={!enabled||busy} onClick={()=>void issueCommand("commit_living_map_fingerprint")}>Commit Tasting Fingerprint</button><button className="btn btn-quiet" disabled={!enabled||busy} onClick={()=>void issueCommand("reopen_living_map")}>Reopen briefly</button></>}
      </div>
      {session.status==="replaying"&&<div className="host-living-map-replay"><label htmlFor={`host-map-replay-${eventId}`}>Watch tasting evolve · {formatClock(replayPosition)}</label><input id={`host-map-replay-${eventId}`} type="range" min={0} max={session.durationSeconds*1000} step={1000} value={Math.min(session.durationSeconds*1000,session.replayPausedAt?seek:replayPosition)} onChange={event=>setSeek(Number(event.target.value))} onPointerUp={()=>void issueCommand("seek_living_map_replay",{replayPositionMs:seek})}/><div>{LIVING_MAP_PROMPTS.map(prompt=><button type="button" key={prompt.atMs} disabled={!enabled||busy} onClick={()=>{setSeek(prompt.atMs);void issueCommand("seek_living_map_replay",{replayPositionMs:prompt.atMs})}}>{formatClock(prompt.atMs)}</button>)}</div></div>}
      {snapshot?.generatedPatterns.length?<div className="living-map-patterns"><strong>Neutral pattern statements</strong><ul>{snapshot.generatedPatterns.map(pattern=><li key={pattern}>{pattern}</li>)}</ul></div>:null}
      {session.status==="committed"&&<div className="notice success"><strong>Tasting Fingerprint committed.</strong> The final projection and replay manifest are now preserved as this room’s session artifact.</div>}
      {snapshot?.projection.items.some(item=>item.isCustom)&&<details className="host-living-map-moderation"><summary>Review personal phrases</summary><p className="help">Hide changes the shared projection and leaves an audit record. It never deletes the underlying observation event.</p>{snapshot.projection.items.filter(item=>item.isCustom).map(item=><div className="row" key={`${item.layer}:${item.key}`}><span>{item.label} · {item.layer}</span><span className="spacer"/><button className="btn btn-quiet" disabled={!enabled||busy} onClick={()=>void moderate(item.key,"hide")}>Hide from map</button></div>)}{moderationError&&<div className="notice error" role="alert">{moderationError}</div>}</details>}
    </>}
  </section>;
}

function formatClock(ms:number){const seconds=Math.max(0,Math.ceil(ms/1000));return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}
