import Link from "next/link";
import { CouponBuilder } from "@/components/admin/CouponBuilder";
import { CouponLifecycleActions } from "@/components/admin/CouponLifecycleActions";
import { StoreConnectionNotice } from "@/components/admin/StoreConnectionNotice";
import { cad, couponStatuses, loadCoupon, loadCouponCatalog, loadCouponRedemptions, loadCouponReport, loadCouponReviewHolds, loadCoupons, loadCouponSummary, type CouponAggregate, type CouponCatalog, type CouponDetail, type CouponRedemption, type CouponReportRow, type CouponReviewHold, type CouponSummary } from "@/lib/admin/coupons";
import { requireStaff } from "@/lib/auth";
import { authorizedCommerceClient } from "@/lib/supabase/commerce-server";

export const dynamic = "force-dynamic";
type Params = { status?: string; search?: string; coupon?: string; mode?: string; listCursor?: string; redemptionCursor?: string; reportCursor?: string; reviewCursor?: string; from?: string; to?: string; catalogSearch?: string };
const title = (value: string) => value.replaceAll("_", " ").replace(/^./, (c) => c.toUpperCase());
const encodeCursor=(value:Record<string,string>)=>Buffer.from(JSON.stringify(value)).toString("base64url");
const decodeCursor=(value:string|undefined)=>{ try { if(!value||value.length>500)return {}; const parsed=JSON.parse(Buffer.from(value,"base64url").toString()); return parsed&&typeof parsed==="object"?parsed:{}; } catch{return {};} };
const href=(params:Params,changes:Record<string,string|null>)=>{ const q=new URLSearchParams(); for(const [key,value] of Object.entries(params))if(value)q.set(key,value); for(const [key,value] of Object.entries(changes)){if(value===null)q.delete(key);else q.set(key,value);} return `/admin/coupons${q.size?`?${q}`:""}`; };
const validDay=(value:unknown)=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).valueOf());
export default async function CouponsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const staff = await requireStaff(["admin"]), params = await searchParams;
  const client = await authorizedCommerceClient(staff.user.id); if (!client) return <StoreConnectionNotice/>;
  const today=new Date().toISOString().slice(0,10), prior=new Date(Date.now()-30*86400_000).toISOString().slice(0,10);
  const fromDay=validDay(params.from)?params.from!:prior,toDay=validDay(params.to)?params.to!:today;
  const from=`${fromDay}T00:00:00Z`,to=new Date(`${toDay}T00:00:00Z`);to.setUTCDate(to.getUTCDate()+1);const toIso=to.toISOString();
  const listLimit=25,reportLimit=25,reviewLimit=25,redemptionLimit=25;
  let coupons:CouponSummary[]=[],catalog:CouponCatalog={products:[],categories:[],customers:[]},detail:CouponDetail|null=null,redemptions:CouponRedemption[]=[],report:CouponReportRow[]=[],reviewHolds:CouponReviewHold[]=[];
  let aggregate:CouponAggregate={availableNow:0,needsReview:0,redemptions:0,discountCents:0,grossPaidCents:0,refundedCents:0,netRevenueCents:0},error="";
  if(params.coupon)try{detail=await loadCoupon(client,params.coupon);}catch{error="That coupon could not be loaded. Return to the coupon list and try again.";}
  try { [coupons,report,aggregate,reviewHolds,catalog]=await Promise.all([
    loadCoupons(client,{status:params.status,search:params.search,cursor:decodeCursor(params.listCursor),limit:listLimit}),
    loadCouponReport(client,from,toIso,decodeCursor(params.reportCursor),reportLimit),loadCouponSummary(client,from,toIso),
    loadCouponReviewHolds(client,decodeCursor(params.reviewCursor),reviewLimit),loadCouponCatalog(client,{search:params.catalogSearch,definition:detail?.definition}),
  ]); } catch { error ||= "Coupon data is temporarily unavailable. Refresh to try again."; }
  if(detail)try{redemptions=await loadCouponRedemptions(client,detail.couponId,decodeCursor(params.redemptionCursor),redemptionLimit);}catch{error="Redemptions could not be loaded for this coupon.";}
  const listNext=coupons.at(-1),redemptionNext=redemptions.at(-1),reportNext=report.at(-1),reviewNext=reviewHolds.at(-1);
  return <main className="admin-page coupon-admin"><div className="admin-page-heading"><div><p className="eyebrow">Commerce</p><h1>Coupons</h1><p>Create offers, control who can use them, and review their results.</p></div><Link className="btn btn-gold" href="/admin/coupons?mode=new" prefetch={false}>Create coupon</Link></div>
    {error&&<div className="admin-commerce-notice" role="alert">{error}</div>}
    <section className="coupon-kpis" aria-label="Coupon summary"><article><span>Available now · all coupons</span><strong>{aggregate.availableNow}</strong></article><article><span>Redemptions · chosen range</span><strong>{aggregate.redemptions}</strong></article><article><span>Discounts · chosen range</span><strong>{cad(aggregate.discountCents)}</strong></article><article><span>Needs review · all holds</span><strong>{aggregate.needsReview}</strong></article></section>
    {(params.mode==="new"||detail)&&<section className="admin-panel coupon-editor"><div className="admin-panel-heading"><div><p className="eyebrow">{detail?detail.code:"New offer"}</p><h2>{detail?`Edit ${detail.name}`:"Create a coupon"}</h2></div><Link href="/admin/coupons" prefetch={false}>Close editor</Link></div><form action="/admin/coupons" className="admin-order-search"><input type="hidden" name={detail?"coupon":"mode"} value={detail?.couponId??"new"}/><label htmlFor="catalog-search">Find picker options</label><input id="catalog-search" name="catalogSearch" defaultValue={params.catalogSearch??""} placeholder="Product or customer"/><button className="btn btn-secondary">Search</button></form><CouponBuilder key={`${detail?.couponId??"new"}:${detail?.version??0}`} catalog={catalog} coupon={detail??undefined}/></section>}
    {detail&&<CouponLifecycleActions coupon={detail}/>}
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">All promotions</p><h2>Coupon list</h2></div></div><form action="/admin/coupons" className="admin-order-search"><label htmlFor="coupon-search">Search</label><input id="coupon-search" name="search" defaultValue={params.search??""}/><select aria-label="Coupon status" name="status" defaultValue={couponStatuses.includes(params.status as never)?params.status:""}><option value="">All statuses</option>{couponStatuses.map((status)=><option value={status} key={status}>{title(status)}</option>)}</select><button className="btn btn-secondary">Filter</button></form>
      <div className="coupon-table-wrap"><table className="coupon-table"><thead><tr><th>Code</th><th>Status</th><th>Visibility</th><th>Uses</th><th>Review</th><th>Updated</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{coupons.map((coupon)=><tr key={coupon.couponId}><td><strong>{coupon.code}</strong><small>{coupon.name}</small></td><td><span className={`coupon-status is-${coupon.status}`}>{title(coupon.status)}</span></td><td>{coupon.visibility==="public"?"Public":"Private"}</td><td>{coupon.redemptions}</td><td>{coupon.needsReview||"—"}</td><td>{new Date(coupon.updatedAt).toLocaleDateString("en-CA")}</td><td><Link href={`/admin/coupons?coupon=${coupon.couponId}`} prefetch={false}>Edit</Link></td></tr>)}</tbody></table>{!coupons.length&&!error&&<p>No coupons match this view.</p>}</div><nav className="admin-order-pagination" aria-label="Coupon pages">{params.listCursor&&<Link className="btn btn-secondary" href={href(params,{listCursor:null})}>Newest</Link>}{coupons.length===listLimit&&listNext&&<Link className="btn btn-secondary" href={href(params,{listCursor:encodeCursor({updatedAt:listNext.updatedAt,couponId:listNext.couponId})})}>Older coupons</Link>}</nav>
    </section>
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Payment reconciliation</p><h2>Coupon holds needing review</h2></div></div><p>These holds remain counted toward usage limits because payment state is uncertain. Reconcile them through the existing provider and order recovery tools; this page does not release holds.</p><div className="coupon-table-wrap"><table className="coupon-table"><thead><tr><th>Coupon</th><th>Attempt</th><th>Provider</th><th>Customer</th><th>Discount</th><th>Reason</th></tr></thead><tbody>{reviewHolds.map(row=><tr key={row.reservationId}><td>{row.code}</td><td><code>{row.attemptId.slice(0,8)}</code><small>{row.attemptStatus}</small></td><td>{row.paymentProvider}</td><td>{row.normalizedEmail}</td><td>{cad(row.discountCents)}</td><td>{row.reviewReason||"Ambiguous payment state"}</td></tr>)}</tbody></table>{!reviewHolds.length&&<p>No coupon holds need review.</p>}</div><nav className="admin-order-pagination" aria-label="Review hold pages">{params.reviewCursor&&<Link className="btn btn-secondary" href={href(params,{reviewCursor:null})}>Newest</Link>}{reviewHolds.length===reviewLimit&&reviewNext&&<Link className="btn btn-secondary" href={href(params,{reviewCursor:encodeCursor({createdAt:reviewNext.createdAt,reservationId:reviewNext.reservationId})})}>Older holds</Link>}</nav></section>
    {detail&&<section className="admin-panel"><h2>{detail.code} redemptions</h2><div className="coupon-table-wrap"><table className="coupon-table"><thead><tr><th>Order</th><th>Customer</th><th>Discount</th><th>Redeemed</th></tr></thead><tbody>{redemptions.map(row=><tr key={row.reservationId}><td>#{row.orderNumber}</td><td>{row.normalizedEmail||row.customerKey}</td><td>{cad(row.discountCents)}</td><td>{new Date(row.redeemedAt).toLocaleString("en-CA")}</td></tr>)}</tbody></table>{!redemptions.length&&<p>No redemptions on this page.</p>}</div><nav className="admin-order-pagination" aria-label="Redemption pages">{params.redemptionCursor&&<Link className="btn btn-secondary" href={href(params,{redemptionCursor:null})}>Newest</Link>}{redemptions.length===redemptionLimit&&redemptionNext&&<Link className="btn btn-secondary" href={href(params,{redemptionCursor:encodeCursor({redeemedAt:redemptionNext.redeemedAt,reservationId:redemptionNext.reservationId})})}>Older redemptions</Link>}</nav></section>}
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Chosen reporting range</p><h2>Coupon performance</h2></div></div><form action="/admin/coupons" className="admin-order-search"><label>From (UTC)<input type="date" name="from" defaultValue={fromDay}/></label><label>Through (UTC)<input type="date" name="to" defaultValue={toDay}/></label><button className="btn btn-secondary">Update report</button></form><p>Summary totals above cover every redemption from {fromDay} through {toDay}. The table is paginated by coupon.</p><div className="coupon-table-wrap"><table className="coupon-table"><thead><tr><th>Coupon</th><th>Redemptions</th><th>Discounts</th><th>Gross paid</th><th>Refunded</th><th>Net revenue</th></tr></thead><tbody>{report.map(row=><tr key={row.code}><td><strong>{row.code}</strong><small>{row.name}</small></td><td>{row.redemptions}</td><td>{cad(row.discountCents)}</td><td>{cad(row.grossPaidCents)}</td><td>{cad(row.refundedCents)}</td><td>{cad(row.netRevenueCents)}</td></tr>)}</tbody></table>{!report.length&&!error&&<p>No coupon redemptions in this period.</p>}</div><nav className="admin-order-pagination" aria-label="Report pages">{params.reportCursor&&<Link className="btn btn-secondary" href={href(params,{reportCursor:null})}>First page</Link>}{report.length===reportLimit&&reportNext&&<Link className="btn btn-secondary" href={href(params,{reportCursor:encodeCursor({code:reportNext.code})})}>More coupons</Link>}</nav></section>
  </main>;
}
